config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: { registrations: :registrations }
  root 'news#index'

  # get 'components/index'
  # root 'components#index'

  # post :toggle, to: 'locales#toggle'
  #resource :profile, only: [:edit, :update, :show]
  get :user, to: 'users#index'
  get 'user/edit', to: 'users#edit'
  get 'user/index', to: 'users#index'
  # patch 'user/edit', to: 'users#update'
  # resource :user, only: [:edit, :update, :show]
  # resources :news
  post :simple_rating, to: 'news#simple_rating'

  get 'user/news/new', to: 'news#new'
  get 'user/news/edit/:id', to: 'news#edit', as: 'user_news_edit'
  get 'user/news/:id', to: 'news#show', as: 'user_news_show'
  get 'user/news', to: 'news#index', as: 'user_news_index'

  #get 'user/profile/edit', to: 'profiles#edit'
  # namespace :user do
  #   resources :news
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }


  # devise_scope :user do
  #   get "/login" => "devise/sessions#new"
  # end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        post :sign_in, to: 'sessions#create_session'
        #delete :sign_out, to: 'sessions#destroy'
        get :sign_out, to: 'sessions#destroy'
        get :current_user, to: 'sessions#current_user_api'
        #get :user, to: 'registrations#edit'
      end
    end
  end

  resources :news

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :comments, only: [:index, :show, :create, :destroy]
      get 'comments/:news_id/show', to: 'comments#show'
    end
  end
end

app/views/layouts/_bottom_menu.html.slim
.navbar.fixed-bottom
  ul.nav.navbar-nav.navbar-right id="id_copyright"
    li.navbar-item 2022 Copyright: anything.some

app/views/layouts/_left_menu.html.slim
nav.sidebar.close
  header
    .image-text
      span.image
        = image_tag('logo/ruby-fiolent.png', class:'d-block', alt: 'logo')
        /img alt="" src="logo.png" /
      .text.logo-text
        span.name Ruby on Rails
        span.profession News maker
    i.bx.bx-chevron-right.toggle
  .menu-bar
    .menu
      li.search-box
        i.bx.bx-search.icon
        input placeholder="Search..." type="text" /
      ul.menu-links
        li.nav-link
          a href="#" 
            i.bx.bx-home-alt.icon
            span.text.nav-text Dashboard
        li.nav-link
          = link_to user_edit_path, method: :get do  
            i.bx.bx-user-circle.icon
            span.text.nav-text Profile
            /<i class='bx bxs-user-circle'></i>
        li.nav-link
          = link_to user_news_index_path, method: :get do 
            i.bx.bx-bar-chart-alt-2.icon
            span.text.nav-text News
        li.nav-link
          a href="#" 
            i.bx.bx-bell.icon
            span.text.nav-text Notifications
        li.nav-link
          a href="#" 
            i.bx.bx-pie-chart-alt.icon
            span.text.nav-text Analytics
        li.nav-link
          a href="#" 
            i.bx.bx-heart.icon
            span.text.nav-text Likes
        li.nav-link
          a href="#" 
            i.bx.bx-wallet.icon
            span.text.nav-text Wallets
    .bottom-content
      li
        = link_to toggle_path, method: :post do
          i.bx.bx-globe.icon
          span.text.nav-text 
            = t('label.localization')
      li
        = link_to destroy_user_session_path, method: :delete do
          i.bx.bx-log-out.icon
          span.text.nav-text
            = t('label.log_out')
      li.mode
        .sun-moon
          i.bx.bx-moon.icon.moon
          i.bx.bx-sun.icon.sun
        span.mode-text.text Dark mode
        .toggle-switch
          span.switch
section.home
  .text
    = current_user.name
  .user-content
    = yield

app/views/layouts/_top_menu.html.slim
= stylesheet_link_tag 'layouts'
nav.navbar.navbar-expand-lg
  .container-fluid
    a.navbar-brand[href="#"]
      /= link_to_unless_current('FE', { controller: "/home", action: "index" }, class: "nav-link"){ link_to('FE', { controller: "home", action: "index" }, class: "nav-link disabled") }
    button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        li.nav-item
          = link_to_unless_current(t('news'), { controller: "/news", action: "index" }, class: "nav-link") { link_to(t('news'), { controller: "news", action: "index" }, class: "nav-link disabled") } 
      /   li.navbar-item
      /     = link_to_unless_current( t('top-menu.stats'), { controller: "/stats", action: "index" }, class: "nav-link"){ link_to( t('top-menu.stats'), { controller: "stats", action: "index" }, class: "nav-link disabled") }
      /   - if current_user && current_user.admin?
      /     li.navbar-item
      /       = link_to_unless_current( t('top-menu.admin'), { controller: "/admin/users", action: "index" }, class: "nav-link"){ link_to( t('top-menu.admin'), { controller: "admin/users", action: "index" }, class: "nav-link disabled") }
      /   li.navbar-item
      /     = link_to_unless_current( t('top-menu.about'), { controller: "/about", action: "index" }, class: "nav-link"){ link_to( t('top-menu.about'), { controller: "stats", action: "index" }, class: "nav-link disabled") }         
      ul.navbar-nav.ms-auto.mb-2.mb-lg-0
        - if user_signed_in?
          li.nav-item.dropdown
            a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" href="#" role="button" 
              = current_user.name
            ul.dropdown-menu.dropdown-menu-end role="menu" aria-labelledby="navbarDropdown" 
              /- if current_user.default?
              li
                = link_to t('label.edit_profile'), user_path, class: "nav-link"
              li
                = link_to "#{t('label.localization')} [#{language_link_name}]", toggle_path, class: "nav-link", method: :post
              li
                = link_to t('label.log_out'), destroy_user_session_path, class: "nav-link", method: :delete
        / li.nav-item
        / - if current_user.avatar.attached?
        /   = image_tag current_user.avatar.variant(resize: '50x50'), class: 'img-fluid rounded-circle'
        / - else
        /   i.fa.fa-user style='font-size:28px; color: rgb(142, 187, 254);'       
        - else
          li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" href="#" role="button" 
            = t('label.come_in')
          ul.dropdown-menu.dropdown-menu-end aria-labelledby="navbarDropdown" 
            li
              = link_to t('label.log_in'), new_user_session_path, class: "nav-link"
            li
              = link_to t('label.registration'), new_user_registration_path, class: "nav-link"
            li 
              = link_to "#{t('label.localization')} [ #{language_link_name} ]", toggle_path, class: "nav-link", id: "localization_link", method: :post

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todo
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    /= stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    /= javascript_pack_tag 'application','data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
    /= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    /= javascript_importmap_tags("apllication", shim: !ENV["CI"])
    = javascript_importmap_tags
  body
    #root
    / - if request.path.split('/').include?('user')
    /   = render "layouts/left_menu"
    /     /= yield
    / - else
    /   .wrapper
    /     .header
    /       = render "layouts/top_menu"
    /     .content
    /       = yield
    /     .footer
    /       = render "layouts/bottom_menu"

/ <%# <!DOCTYPE html>
/ <html>
/   <head>
/     <title>
/       Todo
/     </title><meta content="width=device-width,initial-scale=1" name="viewport" />
/     <%= csrf_meta_tags %>
/     <%= csp_meta_tag %>
/     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
/     <%= stylesheet_link_tag "https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css" %>
/     <%= javascript_importmap_tags %>
/   </head>
/   <body ref="bodyRef">
/     <div id="root">
/     </div>
/   </body></html> %>